import { ClubDetail } from "../types/clubTypes";
export const exampleClubListData: Array<ClubDetail> = [
  {
    ClubID: 2128,
    ClubName: "Woking",
    ClubAddress: "Kingfield Road, Woking, Surrey, GU22 9AA",
    ContactEmailAddr: null,
    ClubLogo: "WokingLogo.png",
    MainWebsite: "http://www.wokingfc.co.uk/",
    UrlFriendlyName: "woking",
    PyramidId: "1112",
    PyramidName: "national league",
    Nicknames: "The cardinals",
    Active: true,
    ClubGuid: "3cefd4b0-110c-4f98-9a41-6b288713f9d9",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Woking_F.C." },
      { SocialType: "twitter", SocialLink: "wokingfc" },
      { SocialType: "facebook", SocialLink: "wokingfc" },
      { SocialType: "instagram", SocialLink: "wokingfc" },
    ],
  },
  {
    ClubID: 2106,
    ClubName: "Aldershot Town",
    ClubAddress: "EBB Stadium, High street, Aldershot, GU11 1TW",
    ClubLogo: "AldershotTownLogo.png",
    MainWebsite: "http://www.theshots.co.uk/",
    UrlFriendlyName: "aldershot-town",
    PyramidId: "1112",
    PyramidName: "national league",
    Nicknames: "The Shots",
    Active: true,
    ClubGuid: "472cd85a-8341-4444-97c2-959a0a4c07c9",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Aldershot_Town_F.C." },
      { SocialType: "twitter", SocialLink: "OfficialShots" },
      { SocialType: "facebook", SocialLink: "AldershotTownFC" },
    ],
  },
  {
    ClubID: 3089,
    ClubName: "Southend United FC",
    ClubAddress:
      "Roots Hall Football Stadium, Victoria Ave, Westcliff-on-Sea, Southend-on-Sea, SS2 6NQ",
    ContactEmailAddr: null,
    ClubLogo: "SouthendUnitedLogo.png",
    MainWebsite: "https://www.southendunited.co.uk/",
    UrlFriendlyName: "southend-united-fc",
    PyramidId: "1112",
    PyramidName: "national league",
    Nicknames: null,
    Active: true,
    ClubGuid: "7f3cbbe3-7018-4fd7-8f35-6d608394eab3",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Southend_United_F.C." },
      { SocialType: "twitter", SocialLink: "SUFCRootsHall" },
      { SocialType: "facebook", SocialLink: "SouthendUnitedFC" },
      { SocialType: "instagram", SocialLink: "SUFCRootsHall" },
    ],
  },
  {
    ClubID: 2397,
    ClubName: "Dorking Wanderers FC",
    ClubAddress:
      "Meadowbank Football Ground, Mill Lane,  Dorking, Surrey, RH4 1DX",
    ClubLogo: "DorkingWanderersFCLogo.png",
    MainWebsite: "http://www.dorkingwanderers.com/",
    UrlFriendlyName: "dorking-wanderers-fc",
    PyramidId: "1084",
    PyramidName: "national league south",
    Nicknames: "Wanderers",
    Active: true,
    ClubGuid: "7a30fcff-5d17-4d5c-ba0e-86e443a5d93c",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Dorking_Wanderers_F.C." },
      { SocialType: "twitter", SocialLink: "DorkingWDRS" },
      { SocialType: "facebook", SocialLink: "DorkingWanderers" },
    ],
  },
  {
    ClubID: 2733,
    ClubName: "Knaphill FC",
    ClubAddress:
      "Brookwood Country Park Football Ground, Redding Way, Knaphill, Woking, Surrey, GU21 2AY",
    ClubLogo: "KnaphillFCLogo.png",
    MainWebsite: "http://www.pitchero.com/clubs/knaphillfootballclub/",
    UrlFriendlyName: "knaphill-fc",
    PyramidId: "1117",
    PyramidName: "combined counties football league premier division south",
    Nicknames: "The Knappers",
    Active: true,
    ClubGuid: "df0cbdf1-41a8-4fcb-a307-83e47afea8ff",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Knaphill_F.C." },
      { SocialType: "twitter", SocialLink: "knaphillfc" },
      {
        SocialType: "facebook",
        SocialLink: "pages/Knaphill-FC/191217394291007",
      },
    ],
  },
  {
    ClubID: 2423,
    ClubName: "Abbey Rangers FC",
    ClubAddress: "Addlestone Moor, Addlestone, Surrey, KT15 2QH",
    ContactEmailAddr: null,
    ClubLogo: "AbbeyRangersFCLogo.png",
    MainWebsite: "https://www.abbeyrangers.co.uk/",
    UrlFriendlyName: "abbey-rangers-fc",
    PyramidId: "1117",
    PyramidName: "combined counties football league premier division north",
    Nicknames: null,
    Active: true,
    ClubGuid: "73a1f8cc-cac4-4e6d-8044-7fd1a66f3c92",
    SocialLinks: [
      { SocialType: "wikipedia", SocialLink: "Abbey_Rangers_F.C." },
      { SocialType: "twitter", SocialLink: "fc_abbeyrangers" },
    ],
  },
];
